### PR TITLE
Leo: CM'ify

### PR DESCRIPTION
**Pull request by nailyk-fr**
- Change target name to 'z3'
- Change includes to 'device/sony/z3'
- Rename device.mk to cm.mk to be more resiliant with CM process
- Add double tap to wake from https://github.com/tomgus1/android_device_sony_aries/commit/6f5da2928918d89c1c946ef09a493fa85aef753e

Lot of work to do but device is usable.

### CODE REVIEW

**Comment by alviteri** [comment]
Why are you removing device.mk ???

**Comment by nailyk-fr** [comment]
Only renaming. IIRC [somewhere](https://github.com/CyanogenMod/android_build/blob/cm-14.1/core/product_config.mk#L184) into the cm toolchain there is a check for this file and had weird behaviors when cm.mk was not present on first breakfast.

**Comment by AdFad666** [comment]
Do not rename device.mk

**Comment by nailyk-fr** [comment]
Thank. Added into the new [PR](https://github.com/SonyCM/android_device_sony_leo/pull/2).

**Pull request closed without merging**
